[33m[nodemon] 3.0.3[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: py,json[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:35:55] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:35:55] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:35:56] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 62c99f11001df6954d31f1890e3bf9b9).
[2024-02-17 22:36:25] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 58, in on_message
    print(" yn year list: ",  userHereList[1][0])
                              ~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-02-17 22:36:38] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 58, in on_message
    print(" yn year list: ",  userHereList[1][0])
                              ~~~~~~~~~~~~^^^
IndexError: list index out of range
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:37:08] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:37:08] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:37:09] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 203b4f332ac74ff32af4f18301fc2b00).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:37:42] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:37:42] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:37:43] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fb4e1c307f87845cdcfdf381165e8dc4).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:37:43] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:37:43] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:37:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 929bde7cffee6c00545c3b136c907427).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:37:45] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:37:45] [INFO    ] discord.client: logging in using static token
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:37:47] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:37:47] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:37:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d08ba821e9695ebe6b9f9c1fbdac6b02).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:38:17] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:38:17] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:38:18] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bb1190391c395c01538d02cde66161b7).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:38:19] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:38:19] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:38:20] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c26ba39b99d785c42511fc3e0162d46c).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:38:20] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:38:20] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:38:23] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2024-02-17 22:38:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 00785e704958c19e6068dc756684d53f).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:39:26] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:39:26] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:39:26] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c3e0c263965783023f4aa5226b0a4761).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:39:28] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:39:28] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:39:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 033f5553a9e4fdaa051fcadc04ccadf2).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 47
    listSniped = message.mentions
    ^
IndentationError: expected an indented block after 'if' statement on line 46
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:39:38] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:39:38] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:39:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5f8c0ff2e8fd395cb01c1080308166d1).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:39:53] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:39:53] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:39:54] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 605c3e3be3718fd8838178b7fbaf65a0).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 46
    if (len(message.attachments) != 0) and : 
                                           ^
SyntaxError: invalid syntax
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 46
    if (len(message.attachments) != 0) and: 
                                          ^
SyntaxError: invalid syntax
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:40:04] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:40:04] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:40:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4c9ac5053c13919ad6abc0ef38ddc7c5).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:40:05] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:40:05] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:40:08] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3c7e753af338f7218a552ca4c88cc000).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 80
    bot.run(DISCORD_API_TOKEN) #remove this and ENV it later 
IndentationError: expected an indented block after 'else' statement on line 72
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 80
    bot.run(DISCORD_API_TOKEN) #remove this and ENV it later 
IndentationError: expected an indented block after 'else' statement on line 72
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:40:21] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:40:21] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:40:21] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 03d9260e6ff0d3f8dd0116a8646e3539).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:40:26] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:40:26] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:40:27] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b27d4e987622e84a066ea0b83f17fcbf).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:40:42] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:40:42] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:40:43] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 398a1b025f9fb3f14b74980f706d2c9f).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 47
    if 
       ^
SyntaxError: invalid syntax
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 47
    if() 
         ^
SyntaxError: expected ':'
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 47
    if() 
         ^
SyntaxError: expected ':'
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:41:04] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:41:04] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:41:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e7ed60ddfeaa4de40b2ccd4e33bcefc3).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 64
    if len
          ^
SyntaxError: expected ':'
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 64
    if len()
            ^
SyntaxError: expected ':'
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 64
    if len(list)
                ^
SyntaxError: expected ':'
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 64
    if len(list)
                ^
SyntaxError: expected ':'
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 64
    if len(listSniped)
                      ^
SyntaxError: expected ':'
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
  File "/Users/srirammk/Documents/GitHub/snipe-bot/main.py", line 65
    await 
          ^
SyntaxError: invalid syntax
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:41:34] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:41:34] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:41:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5bb2fbaac2d504359cfbc6e56f42bb4c).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:41:48] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:41:48] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:41:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 48ddbc675439823bd78e5e7be8061507).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:41:52] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:41:52] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:41:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 829b45e0d524783c661684c36d98ee4e).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 22:41:53] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 22:41:53] [INFO    ] discord.client: logging in using static token
[2024-02-17 22:41:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a56be0d85a01f9c0a7d842c5ede1713e).
[2024-02-17 22:58:07] [ERROR   ] discord.client: Attempting a reconnect in 0.75s
Traceback (most recent call last):
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/discord/http.py", line 537, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 832, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srirammk/Documents/GitHub/snipe-bot/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-d.discord.gg:443 ssl:default [nodename nor servname provided, or not known]
[2024-02-17 22:58:08] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2024-02-17 22:58:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b7e43092186d26635afc498caf1fe0f4).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 23:46:27] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 23:46:27] [INFO    ] discord.client: logging in using static token
[2024-02-17 23:46:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ed14533abb4e7d4d1b77a6d1af9e56f4).
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 23:47:23] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 23:47:23] [INFO    ] discord.client: logging in using static token
[2024-02-17 23:47:24] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d2234b0f2f03cfe010cbb354ee8e7789).
[32m[nodemon] restarting child process[39m
[32m[nodemon] starting `python3 main.py`[39m
[2024-02-17 23:49:26] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-02-17 23:49:26] [INFO    ] discord.client: logging in using static token
[2024-02-17 23:49:27] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3a119151269617d5f5e93202d12cf064).
